bosh backup release

diff --git a/jobs/pgbackup/templates/bin/pgbackup b/jobs/pgbackup/templates/bin/pgbackup
--- a/jobs/pgbackup/templates/bin/pgbackup
+++ b/jobs/pgbackup/templates/bin/pgbackup
@@ -1,16 +1,15 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-source "$(dirname $(dirname ${0}))/shell/env"
+chmod 777 ../shell/env
+../shell/env
+PATH=/var/vcap/bosh/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 set +e # do not want to auto-die - instead, log and continue
-# FIXME: use pgbackup.debug
-
+# FIXME: use pgbackup.debug --> Not implemented yet
 TIMESTAMP=$(date +%Y/%m/%d/%Y%m%d%H%M%S)
 
 # Environment for postgres commands
-PGHOST="<%= p('pgbackup.host') %>"
-PGPORT="<%= p('pgbackup.port') %>"
-PGUSER="<%= p('pgbackup.username') %>"
-PGPASSWORD="<%= p('pgbackup.password') %>"
+PGHOST="<%= p('pgbackup.host') %>" # host  for the postgres database url
+PGPASSWORD="<%= p('pgbackup.password') %>" #  port associated with the postgres database url
 
 <%
 pgversion = case p('pgbackup.version')
@@ -31,44 +30,69 @@ else
 end
 %>
 
+# ==> pgversion default value will be removed
 PGVERSION="<%= pgversion %>"
-export PGHOST PGPORT PGUSER PGPASSWORD PGVERSION
+export PGHOST PGPASSWORD PGVERSION
 echo "export PGHOST=$PGHOST"
-echo "export PGPORT=$PGPORT"
-echo "export PGUSER=$PGUSER"
 echo "export PGVERSION=$PGVERSION"
 
-PG_DUMP="/var/vcap/packages/${PGVERSION}/bin/pg_dumpall"
+PG_DUMP="/var/vcap/packages/${PGVERSION}/bin/pg_dump"
+
 GOF3R="/var/vcap/packages/gof3r/bin/gof3r"
 
+# S3 bucket access credentials
 AWS_ACCESS_KEY_ID="<%= p('pgbackup.s3.access_key_id') %>"
 AWS_SECRET_ACCESS_KEY="<%= p('pgbackup.s3.secret_access_key') %>"
 export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
 
+# S3 bucket other information
 S3_BUCKET="<%= p('pgbackup.s3.bucket') %>"
 S3_PATH="/<%= p('pgbackup.s3.path') %>"
-S3_ENDPOINT= "<%= p('pgbackup.s3.endpoint') %>"
+S3_ENDPOINT="<%= p('pgbackup.s3.endpoint') %>"
+#get date and time to use it for backup file name
+T=$(date +"%Y-%m-%d__%H-%M")
 
-backup_databases() {
-	local opts="-c --no-password <%= p('pgbackup.pgdump.arguments') %>"
-	local name="<%= p('pgbackup.name') %>"
-
-	s3_file=$(echo "${S3_PATH}/${TIMESTAMP}-${name}.gz" | sed 's|/\+|/|g')
-	echo ">> ${PG_DUMP} ${opts} -> S3 ${S3_BUCKET}:${s3_file}"
-	${PG_DUMP} ${opts} | gzip | ${GOF3R} put --endpoint  "${S3_ENDPOINT}" -b ${S3_BUCKET} -k "${s3_file}"
-
-	if [[ $? == 0 ]]; then
-		echo "backed up successfully"
-	else
-		echo "FAILED to back up!"
-	fi
+log () {
+  level=$1
+  msg=$2
+  logger -t "$LOGGER_TAG" -p user.$level "[$T] $msg"
 }
 
+backup_databases() {
+        # Acquire a lock to ensure we aren't running simultaneous dumps
+        echo "backup in progress "  > /tmp/backup.lock
+        local opts="--endpoint=${S3_ENDPOINT}"
+        local name="<%= p('pgbackup.name') %>"
+        s3_file=$(echo "${name}-$T".gz | sed 's|/\+|/|g' )
+        dump_file="$name.dump"
+        ${PG_DUMP} --username="<%= p('pgbackup.username') %>" --port="<%= p('pgbackup.port') %>" -f $dump_file
+        # Verify the creation of the backup file
+        if [[ $? == 0 ]]; then
+                log "ERROR" "$T : Failed to dump database, you may verify the database user/password credentials"
+        fi
+        gzip $dump_file
+        mv "$dump_file.gz" $s3_file
+        ${GOF3R}  cp  ${opts} "$s3_file" s3://"$S3_BUCKET/$s3_file" >/dev/null 2>&1
+        # ETag-hash comparison always fail, so related error is skipped
+        # see more : Etag-hash s3 multipart
+        echo "backed up successfully"
+        rm $s3_file
+
+}
+
+
 echo "pgbackup starting up"
-# FIXME: acquire a lock to ensure we aren't running simultaneous dumps
+# Test if there is no current backup
+# if a backup.lock file exist then we assume that an other dump is running, so we will retry to backup in the next run
 
-backup_databases
+if [ ! -f "/temp/backup.lock" ]; then
+    backup_databases
+else
+    log "WARNING : an other dump is running or the last backup failed , see logs for more details "
+fi
 
-# FIXME: release lock for the next run
+# release lock for the next run
+rm -f backup.lock
+
 echo "pgbackup shutting down"
 exit 0
