update release

diff --git a/jobs/pgbackup/templates/bin/pgbackup b/jobs/pgbackup/templates/bin/pgbackup
--- a/jobs/pgbackup/templates/bin/pgbackup
+++ b/jobs/pgbackup/templates/bin/pgbackup
@@ -54,7 +54,6 @@ end
 PGVERSION="<%= pgversion %>"
 export PGHOST PGPORT PGUSER PGPASSWORD PGVERSION
 
-
 PG_DUMP="/var/vcap/packages/${PGVERSION}/bin/pg_dumpall"
 GOF3R="/var/vcap/packages/gof3r/bin/gof3r"
 
@@ -70,7 +69,7 @@ echo "export PGHOST=$PGHOST"
 echo "export PGPORT=$PGPORT"
 echo "export PGUSER=$PGUSER"
 echo "export PGVERSION=$PGVERSION"
-echo "use S3_ENDPOINT=$S3_ENDPOINT"
+echo "export S3_ENDPOINT=$S3_ENDPOINT"
 
 # activate debug mode implies storing passwords in logs file,
 # don't forget to disable it
@@ -96,13 +95,13 @@ fi
 backup_databases() {
     # Acquire a lock to ensure we aren't running simultaneous dumps
     echo "backup in progress"  > /tmp/backup.lock
-	local opts="-c --no-password <%= p('pgbackup.pgdumpall.arguments') %>"
+	local opts="-c --no-password <%= p('pgbackup.arguments') %>"
 	local name="<%= p('pgbackup.name') %>"
 
 	s3_file=$(echo "${S3_PATH}/${TIMESTAMP}-${name}.gz" | sed 's|/\+|/|g')
 	echo ">> ${PG_DUMP} ${opts} -> S3 ${S3_BUCKET}:${s3_file}"
-	${PG_DUMP} ${opts} | gzip | ${GOF3R} put --endpoint  "${S3_ENDPOINT}" -b ${S3_BUCKET} -k "${s3_file}"
-
+	${PG_DUMP} ${opts} | gzip | ${GOF3R} put --endpoint  "${S3_ENDPOINT}" -b ${S3_BUCKET} -k "${s3_file}" >/dev/null 2>&1
+    sleep 0
 	if [[ $? == 0 ]]; then
 		echo "backed up successfully"
 	else
@@ -116,34 +115,50 @@ backup_databases() {
 
 backup_single_database(){
     # override environment variables needed for pg_dump
+
     PG_DUMP="/var/vcap/packages/${PGVERSION}/bin/pg_dump"
     PGHOST="<%= p('pgbackup.pgdump.host') %>"
     PGPORT="<%= p('pgbackup.pgdump.port') %>"
     PGUSER="<%= p('pgbackup.pgdump.username') %>"
     PGPASSWORD="<%= p('pgbackup.pgdump.password') %>"
+    PGDATABASE="<%= p('pgbackup.pgdump.database') %>"
+    export PGHOST PGPORT PGUSER PGPASSWORD PGVERSION PGDATABASE
 
-    export PGHOST PGPORT PGUSER PGPASSWORD PGVERSION
+    echo "export PGHOST=$PGHOST"
+    echo "export PGPORT=$PGPORT"
+    echo "export PGUSER=$PGUSER"
+    echo "export PGVERSION=$PGVERSION"
+    echo "export PGDATABASE=$PGDATABASE"
+    echo "export S3_ENDPOINT=$S3_ENDPOINT"
 
+    # activate debug mode implies storing passwords in logs file,
+    # don't forget to disable it
+    debug_mode="<%= p('pgbackup.pgdump.debug') %>"
+    if [[ $debug_mode == "true" ]]; then
+    echo "(debug mode) export  PGPASSWORD=$PGPASSWORD"
+    echo "(debug mode) export  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
+    echo "(debug mode) export  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
+    set -x
+    fi
+    # backup process
+    local opts="<%= p('pgbackup.pgdump.arguments') %>"
     # Acquire a lock to ensure we aren't running simultaneous dumps
     echo "backup in progress"  > /tmp/backup.lock
-    local opts="--endpoint=${S3_ENDPOINT}"
-    local name="<%= p('pgbackup.name') %>"
+
+    local name="<%= p('pgbackup.pgdump.database') %>"
     s3_file=$(echo "${S3_PATH}/${TIMESTAMP}-${name}.gz" | sed 's|/\+|/|g')
-    dump_file="$name.dump"
-    ${PG_DUMP} ${EXTRA_ARG}  -f "${DUMP_DIR}${dump_file}"
-    # Verify the creation of the backup file
-    if [[ $? != 0 ]]; then
-        echo "ERROR Failed to dump database, you may verify the database user/password credentials"
-    fi
-    gzip "${DUMP_DIR}${dump_file}"
-    mv "${DUMP_DIR}${dump_file}.gz" "${DUMP_DIR}${s3_file}"
-    ${GOF3R}  cp  ${opts} "${DUMP_DIR}$s3_file" s3://"$S3_BUCKET/$s3_file" >/dev/null 2>&1
-    # ETag-hash comparison always fail, so related error is skipped
-    # see more : Etag-hash s3 multipart
-    echo "backed up successfully"
-    rm ${DUMP_DIR}$s3_file
+	echo ">> ${PG_DUMP} ${opts} -> S3 ${S3_BUCKET}:${s3_file}"
+	${PG_DUMP} ${opts} | gzip | ${GOF3R} put --endpoint  "${S3_ENDPOINT}" -b ${S3_BUCKET} -k "${s3_file}" >/dev/null 2>&1
+    sleep 0
+	if [[ $? == 0 ]]; then
+		echo "backed up successfully"
+	else
+		echo "FAILED to back up!"
+	fi
     # release the lock for the next run
     rm -f "/tmp/backup.lock"
+    #
+
 }
 
 
